### PR TITLE
Bene Media - D9 Compatibility

### LINKED ISSUE #26: Remove unnecessary dependencies
Media Entity, Media Entity Actions, Media Entity document, and Media entity image are listed as dev requirements for this module and so keep popping up in the FEAM D9 status updates page, though they can't be removed from the project itself. Upon digging in the code, it looks like these aren't necessary anymore. Some functions have been written to automatically disable them, which makes me wonder if they even need to be in the composer.json file.

### PR DESCRIPTION
**Pull request by katieescoto**
@mariacha @unclegcb The following changes should be included here:

- Removed core: line from info.yml files
- Added core_version_requirement line
- Removed outdated dependencies
- Replaced deprecated functions

I think this should make this module d9 compatible

### CODE REVIEW

**Review by mariacha — APPROVED** [review]
Code all looks great to me! I didn't test it on a site, but I can do so on HSUS in this ticket: https://github.com/thinkshout/hsus/issues/1335

**Review by unclegcb — APPROVED** [review]
Looks good here! @mariacha do you want to wait until you've done that test to merge? Should we leave it assigned to you?

**Comment by mariacha** [comment]
I don't think I need to be a blocker. :)

**Comment by mariacha** [comment]
The ticket associated with this for HSUS looks good to me so I'm merging!

**Pull request merged**
